name: Deploy to Lightsail

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/lightsail.pem
          chmod 600 ~/.ssh/lightsail.pem
          
      - name: Debug Connection Info
        run: |
          echo "Current IP address:"
          curl -s ifconfig.me
          echo -e "\nTesting DNS resolution:"
          nslookup 54.218.163.9
          echo -e "\nTesting basic connectivity:"
          ping -c 4 54.218.163.9 || true
          echo -e "\nChecking route:"
          traceroute 54.218.163.9 || true
          echo -e "\nChecking SSH port:"
          nc -zv 54.218.163.9 22 -w 5 || true
          echo -e "\nSSH verbose test:"
          ssh -v -i ~/.ssh/lightsail.pem -o StrictHostKeyChecking=no ec2-user@54.218.163.9 'echo test' || true

      - name: Deploy to Lightsail
        run: |
          # Try direct SSH first
          if ssh -i ~/.ssh/lightsail.pem -o StrictHostKeyChecking=no ec2-user@54.218.163.9 'echo "SSH connection successful"'; then
            echo "SSH connection successful, proceeding with deployment..."
            
            # Create directory
            ssh -i ~/.ssh/lightsail.pem -o StrictHostKeyChecking=no ec2-user@54.218.163.9 'mkdir -p ~/knowledgegraph'
            
            # Sync files
            rsync -e "ssh -i ~/.ssh/lightsail.pem -o StrictHostKeyChecking=no" -av \
                  --exclude '.git' \
                  --exclude '.github' \
                  --exclude 'venv' \
                  --exclude '__pycache__' \
                  --exclude '*.pyc' \
                  ./ ec2-user@54.218.163.9:~/knowledgegraph/
            
            # Execute deployment scripts
            ssh -i ~/.ssh/lightsail.pem -o StrictHostKeyChecking=no ec2-user@54.218.163.9 'cd ~/knowledgegraph && \
                      chmod +x deploy_lightsail.sh && \
                      chmod +x run_daily_sync.sh && \
                      chmod +x setup_cron.sh && \
                      ./deploy_lightsail.sh && \
                      ./setup_cron.sh'
          else
            echo "SSH connection test failed, cannot proceed with deployment"
            exit 1
          fi 