name: Deploy to Lightsail

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Setup SSH and Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 34.219.195.94 > ~/.ssh/known_hosts 2>/dev/null || true
          chmod 600 ~/.ssh/known_hosts
          # Add a more permissive SSH config for initial connection
          echo -e "Host 34.219.195.94\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Deploy to Lightsail
        run: |
          # Test SSH connection first
          ssh -o "StrictHostKeyChecking=no" ec2-user@34.219.195.94 'echo "SSH connection successful"'
          
          # Proceed with deployment
          ssh ec2-user@34.219.195.94 'mkdir -p ~/knowledgegraph'
          rsync -av --exclude '.git' \
                    --exclude '.github' \
                    --exclude 'venv' \
                    --exclude '__pycache__' \
                    --exclude '*.pyc' \
                    ./ ec2-user@34.219.195.94:~/knowledgegraph/
          
          # Make scripts executable and run deployment
          ssh ec2-user@34.219.195.94 'cd ~/knowledgegraph && \
                                     chmod +x deploy_lightsail.sh && \
                                     chmod +x run_daily_sync.sh && \
                                     chmod +x setup_cron.sh && \
                                     ./deploy_lightsail.sh && \
                                     ./setup_cron.sh' 